# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: AHB Decision Support SDK
email: jrmerz@ucdavis.edu
description: >
  Decision Support SDK documentation.  The SDK powers the AHB Decision Support App. 
baseurl: "/ahb-decision-support-sdk" # the subpath of your site, e.g. /blog
url: "http://willow.bioenergy.casil.ucdavis.edu" # the base hostname & protocol for your site
github_username:  cstars

# Build settings
markdown: kramdown
